version: '3.1'

services:

  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./modules/schema/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: gsp
    ports:
      - 5432:5432

